name: First_action
on: 
  push: 
    branches: 
      - master
      
jobs:
  
  job1:
    runs-on: ubuntu-latest
    
    steps:
    - name : Print hello msg job1
      run : echo "Hello world !!!"
      
    - name : job1- run ls -la
      run : ls -la
      
    - name : Clone files
      uses: actions/checkout@v1
      
    - name : job1- run ls -la
      run : ls -la
      
    - name : job1- print test.txt 
      run : |
        echo "First-line"
        echo "Second line"
        echo "Second line again"
        cat test.txt
        
    - name : test secretes
      run : |
        if [ "${{ secrets.sa.SA }}" != "${{ secrets.sa.SB }}" ]; then
          echo "good"
        else
          echo "bad"
        fi
        
  job2:
    runs-on: ubuntu-latest
    
    steps:
    - name : Print ls -la
      run : ls -la
    
    - name : Print hello msg job2
      run : echo "Hello from job2"
      
